add filter for products. Task #3
x0xl0ma/junior-course-boilerplate pull request #3
Opened 2021-05-07 14:42 UTC by x0xl0ma

2021-05-11 07:07 UTC, vislogurov requested changes

2021-05-11 07:07 UTC, vislogurov commented on src/components/ProductsList/ProductsList.js
> +// const ProductsList = ({ items }) => {
Если что-то комментишь, то пиши почему закомменчено. Либо удаляй совсем.

2021-05-11 07:07 UTC, vislogurov commented on src/components/app/App.js
> +    this.setState({ items: products });
`products` же тут будут в том же виде, что и при прямом импорте из json. Нет смысла тут дёргать метод ЖЦ (он будет вызываться каждый рендер, это выглядит избыточным), лучше положить в конструктор.

2021-05-11 07:07 UTC, vislogurov commented on src/components/app/App.js
> +      .filter(item => item.price <= priceMax);
filter может несколько условий принимать) Перенеси его в первый фильтр, и тогда необходимость во втором проходе исчезнет.

2021-05-11 07:07 UTC, vislogurov commented on src/components/button/Button.js
> +const Button = ({ text, onClickHandler }) => {
 Ты вытаскиваешь из пропсов `onClickHandler` ... и куда передаёшь?

2021-05-11 07:07 UTC, vislogurov commented on src/components/button/Button.js
> +        //но всеравно решила оставить
коммент не понял(

2021-05-11 07:07 UTC, vislogurov commented on src/components/priceFilterForm/PriceFilterForm.js
> +// const PriceForm = ({ inputHandler, priceMin, priceMax, buttonHandler }) => {
Тут тоже самое про комменты

2021-05-11 07:07 UTC, vislogurov commented on src/components/priceInput/PriceInput.js
> +      <label className={clsx('price-input-label', additionalClasses)}>
А `additionalClasses` добавляются, когда что происходит?

2021-05-11 12:50 UTC, x0xl0ma commented on src/components/ProductsList/ProductsList.js
> +// const ProductsList = ({ items }) => {
Это лишнее, удалю!

2021-05-11 12:51 UTC, x0xl0ma commented on src/components/app/App.js
> +    this.setState({ items: products });
Поправлю!

2021-05-11 12:51 UTC, x0xl0ma commented on src/components/app/App.js
> +      .filter(item => item.price <= priceMax);
Поправлю!

2021-05-11 12:52 UTC, x0xl0ma commented on src/components/button/Button.js
> +const Button = ({ text, onClickHandler }) => {
Ииии ..... Поправлю!

2021-05-11 12:52 UTC, x0xl0ma commented on src/components/button/Button.js
> +        //но всеравно решила оставить
Сама не поняла, когда прочитала этот бред
Поправлю

2021-05-11 12:59 UTC, x0xl0ma commented on src/components/priceInput/PriceInput.js
> +      <label className={clsx('price-input-label', additionalClasses)}>
Они добавляются, чтобы как-то изменять инпут при переиспользовании. Здесь было сделано, чтобы добавить второму инпуту отступ слева не затрагивая второй инпут

2021-05-11 13:08 UTC, x0xl0ma commented on src/components/priceFilterForm/PriceFilterForm.js
> +// const PriceForm = ({ inputHandler, priceMin, priceMax, buttonHandler }) => {
Тут тоже лишний коммент

2021-05-12 11:20 UTC, vislogurov commented on src/components/priceInput/PriceInput.js
> +      <label className={clsx('price-input-label', additionalClasses)}>
А мы не можем этим рулить на уровне css в конечном компоненте?
```
<div class="form-input">
    <PriceInput />
</div>
```

И нужный отступ добавить классу `form-input`, не прокидывая дополнительный класс внутрь компонента.
А если прокидывать дополнительный класс, то тогда нужно внутри стилей инпута все возможные варианты указывать: в форме один отступ, в форме логина другой отступ, в форме с фильтрами 3й отступ итд.

Инпут должен быть максимально тупым и не знать о том, где он будет юзать в конечном виде. Пусть этим непосредственно сам блок в котором рендерится инпут занимается.

2021-05-12 11:39 UTC, x0xl0ma commented on src/components/priceInput/PriceInput.js
> +      <label className={clsx('price-input-label', additionalClasses)}>
кажется, я чуть перемудрила )

2021-05-13 06:15 UTC, vislogurov approved these changes

2021-05-13 17:41 UTC, merged