add hoc and input discount
x0xl0ma/junior-course-boilerplate pull request #4
Opened 2021-05-16 19:40 UTC by x0xl0ma

2021-05-17 14:23 UTC, vislogurov requested changes

2021-05-17 14:23 UTC, vislogurov commented on src/components/app/App.js
> +      .filter(item => (discount ? item.discount === discount : true));
1) зачем нужен второй проход фильтром?
2) что за условие тут проверяется? и что вернётся, если условие будет false?

2021-05-17 14:23 UTC, vislogurov commented on src/components/app/App.js
> +    const filteredItems = this.state.items
items можно вытащить деструктом выше

2021-05-17 14:23 UTC, vislogurov commented on src/components/app/App.js
> +      .filter(item => (discount ? item.discount === discount : true));
3. неужели не нашлось кандидатов для мемоизации?

2021-05-17 14:33 UTC, x0xl0ma commented on src/components/app/App.js
> +      .filter(item => (discount ? item.discount === discount : true));
> 1. зачем нужен второй проход фильтром? 
- Сначала фильтрую цену, потом скидку
> 2. что за условие тут проверяется? и что вернётся, если условие будет false? 
- наличие скидки в фильтре. Если не введена скидка, те дефолтный 0 - возвращаем все элементы, если скидка есть - фильтруем по скидке. Если оставить просто фильтрацию по скидке, получается, что в дефолтном состоянии, когда скидка 0 - не отображается ни один продукт, те я всем продуктам добавила скидку, и отсюда получилось условие

2021-05-17 14:35 UTC, x0xl0ma commented on src/components/app/App.js
> +      .filter(item => (discount ? item.discount === discount : true));
> 1. неужели не нашлось кандидатов для мемоизации?

по моим представлениям нет. После добавления проверки пропсов, компонент рейтинга перестал перерисовываться как безумный. Остальные перерисовываются согласно графика, если верить консоли

2021-05-17 15:17 UTC, x0xl0ma commented on src/components/app/App.js
> +      .filter(item => (discount ? item.discount === discount : true));
тоже стояло добавить в первый фильтр условием и не городить городули из двух фильтров и тренарника?

2021-05-17 15:25 UTC, vislogurov requested changes

2021-05-17 15:25 UTC, vislogurov commented on src/hoc/wihtInputsHoc.js
> +      this.props.onChange(e, valueAfterCheck);
1)При попытке ввести букву и инпут получаю NaN в качестве значения
http://s.csssr.ru/U0FMPH83W/20210517181433_.png

2) Нужно частям вёрстки задать какие-то минимальные  значения ширины, сейчас, если список пустой, то всё прыгает к середине

2021-05-17 15:25 UTC, vislogurov commented on src/components/app/App.js
> +      .filter(item => (discount ? item.discount === discount : true));
> > 1. зачем нужен второй проход фильтром?
> 
> * Сначала фильтрую цену, потом скидку
> 
> > 1. что за условие тут проверяется? и что вернётся, если условие будет false?
> 
> * наличие скидки в фильтре. Если не введена скидка, те дефолтный 0 - возвращаем все элементы, если скидка есть - фильтруем по скидке. Если оставить просто фильтрацию по скидке, получается, что в дефолтном состоянии, когда скидка 0 - не отображается ни один продукт, те я всем продуктам добавила скидку, и отсюда получилось условие

А почему нельзя это в один проход фильтра сделать? Ты же лишнюю копию массива вторым фильтром создаеёшь

2021-05-17 15:25 UTC, vislogurov commented on src/components/app/App.js
> +      priceMin: 0,
Кстати, вместо нулей мы можем выставить реальные значения минимальной и максимальной цены сразу в инпут — все эти данные уже есть products.
Пользователю будет удобно http://s.csssr.ru/U0FMPH83W/20210517182419_.png
`import {maxBy, minBy} from 'csssr-school-utils'` в помощь

2021-05-19 16:02 UTC, vislogurov approved these changes

2021-05-19 20:02 UTC, merged