Develop
x0xl0ma/junior-course-boilerplate pull request #5
Opened 2021-05-24 18:00 UTC by x0xl0ma

2021-05-26 16:15 UTC, vislogurov requested changes

2021-05-26 16:15 UTC, vislogurov commented on src/components/app/App.js
> +    this.setState({ ...this.state, selectedCategory: categoryName });
На каждый "тык" по фильтрам стейт перезаписывается на новое значение. А что если мы хотим выбрать _комбинацию_ фильтров? "books" и "bestseller" например

2021-05-26 16:15 UTC, vislogurov commented on src/components/category/Category.js
> +          selectedCategory === name ? clsx("category", "selected") : "category"
Думаю пора заняться вопросами изоляции стилей, чтобы получить **абсолютный** БЭМ

1) https://create-react-app.dev/docs/adding-a-css-modules-stylesheet/
2) тут нужно реализовать какую то магию
3) Получаем стили в перевариваемом виде
```
className={
          clsx(styles.category, {
            [styles.selected]: selectedCategory === name
          })
        }
```

2021-05-26 16:15 UTC, vislogurov commented on src/components/priceFilterForm/PriceFilterForm.js
> +        {value => {
`value` значит, что разработчику было лень думать. Предлагаю что-то более конкретное `filterData`?

2021-05-26 16:15 UTC, vislogurov commented on src/components/app/App.js
> +    this.setState({ ...this.state, selectedCategory: categoryFromUrl });
Попробуй повыбирать фильтры, а потом попробуй поперемещаться стрелками по истории...стейт не будет реагировать на изменение фильтров.
P.S обрати внимание на "popstate" в тексте урока

2021-05-26 16:15 UTC, vislogurov commented on src/components/button/Button.js
> +      <button className="simpleButton" onClick={buttonHandler}>
`type` лучше вернуть. Если его не указать в явном виде, то браузер сам будет решать, что именно эта кнопка делает — баги будут самые неожиданные.

2021-05-26 16:15 UTC, vislogurov commented on src/components/button/button.css
> +  transition: ease-in 0.3s;
Указывай явно, что именно хочешь  "транзитить", иначе браузер применит анимация ко всему, что нужно и не нужно

2021-05-26 16:15 UTC, vislogurov commented on src/components/category/Category.js
> +      <button
Почему бы не заюзать тут `Button`, расширив его "закруглённым" стилем?

2021-06-16 13:18 UTC, vislogurov requested changes

2021-06-16 13:18 UTC, vislogurov commented on src/components/category/Category.js
> +      // <button
Если комментишь строки, то пиши зачем. Или удаляй коммент вовсе.

2021-06-16 13:18 UTC, vislogurov commented on src/components/category/Category.js
> +      <Button
По факту Category сейчас это компонент, который рендерит компонент, который рендерит кнопку? Для чего нам такая глубокая вложенность? Category вроде бы не ХОК, не добавляет никакой функицональности на своём уровне.

Получилась обёртка ради обёртки.

2021-06-16 13:18 UTC, vislogurov commented on src/components/category/Category.js
> +        text={name}
Что, если мы захотим отрендерить, например текст и иконкой? Тут лучше children для передачи контента внутрь кнопки.

```
<Button>
 {text/что угодно}
</Button>
```
если абстрактно то это принцип открытости/закрытости, если передавать через чилдов контент, то компонент будет открыт для расширения, но закрыт для изменения.

А если передавать через пропсы, то получается равно обратная ситуация, это признак плохого дизайна кода: типа на каждое изменение контента тебе придется модифицировать Button

2021-06-16 13:18 UTC, vislogurov commented on src/components/category/Category.js
> +        classes={clsx(styles.category, {
Это плохая практика прокидывать css-классы в "тупой" компонент. В попытке достичь независимости компонента кнопки, ты только сильнее усилила связь между Category и Button. Теперь, чтобы где-то ещё получить selected-стиль, нам нужно:
1) Либо дополнительно тащить туда Category
2) Либо копипастить логику расчёта selected опять

Кнопка должна сама в себе инкапсулировать эти стили. А "наружу" только отдавать API, с помощью которого эти стили нужно применить.

```
<Button size="s" color="red" isRounded>
  {text}
</Button>
```
Это удобно на этапе сборки ui-кита в сторибуке — мы сможем сразу видеть все варианты использования кнопки, а не угадывать, как она может от компонента к компоненту меняться.

P.S если у html-элемента есть состояние selected, то это уже не кнопка, а input type="checkbox")))

2021-06-24 11:41 UTC, vislogurov commented on src/components/button/Button.js
> +          [styles.selected]: isSelected
P.S если у html-элемента есть состояние selected, то это уже не кнопка, а input type="checkbox")))

Это важно с точки зрения доступности с клавиатуры.

2021-07-18 15:59 UTC, x0xl0ma commented on src/components/category/Category.js
> +      <button
Теперь у нас тут чекбокс

2021-07-18 15:59 UTC, x0xl0ma commented on src/components/category/Category.js
> +      <Button
И тут тоже чекбокс категорий

2021-07-18 16:00 UTC, x0xl0ma commented on src/components/category/Category.js
> +        text={name}
Здесь все поправила

2021-07-18 16:00 UTC, x0xl0ma commented on src/components/category/Category.js
> +        classes={clsx(styles.category, {
И чекбокс есть, и классов нет

2021-07-18 16:00 UTC, x0xl0ma commented on src/components/button/Button.js
> +          [styles.selected]: isSelected
готовоу

2021-07-23 06:38 UTC, vislogurov approved these changes

2021-07-27 19:01 UTC, merged